-- local windline = require('windline')
-- windline.setup({
--   statuslines = {
--     --- you need define your status line here
--   }
-- })
--
--
--
require('wlsample.airline')
-- require('wlsample.airline_anim')
