#!/bin/bash

SESSION_NAME=diary

tmux has-session -t "$SESSION_NAME"

if [ $? != 0 ]
then
    tmux new-session -s "$SESSION_NAME" -n diary -d

    tmux send-keys -t "$SESSION_NAME" 'nvim' C-m
    tmux send-keys -t "$SESSION_NAME" ':OpenSession diary' C-m
fi
tmux attach -t "$SESSION_NAME"
