#!/bin/bash

SESSION_NAME=simplex
START_DIR=~/Qt/projects/simplex

tmux has-session -t "$SESSION_NAME"

if [ $? != 0 ]
then
    tmux new-session -s "$SESSION_NAME" -n editor -d

    tmux send-keys -t "$SESSION_NAME" "cd $START_DIR" C-m
    tmux send-keys -t "$SESSION_NAME" 'nvim' C-m
    tmux send-keys -t "$SESSION_NAME" ':OpenSession simplex' C-m

    tmux new-window -n console -t "$SESSION_NAME"
    tmux send-keys -t "$SESSION_NAME":2 "cd $START_DIR" C-m

    tmux select-window -t "$SESSION_NAME":1
fi
tmux attach -t "$SESSION_NAME"
