k9s:
  refreshRate: 1
  maxConnRetry: 3
  enableMouse: false
  headless: false
  logoless: true
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 500
    buffer: 5000
    sinceSeconds: -1
    fullScreenLogs: true
    textWrap: false
    showTime: false
  currentContext: kind-local-kind
  currentCluster: kind-local-kind
  clusters:
    kind-local-kind:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - default
      view:
        active: storage
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-tarasov-egor
